function ROI_indices = select_ROIs_from_full_AAL(cfg);
% function ROI_indices = select_ROIs_from_full_AAL(cfg);
% 
% Gives the indices of the ROIs in the AAL atlas that are needed for
% further analysis -- only cortical ROIs
%
% ROI order is the same as in Gong et al. 2009 (Figure 1g and Supplementary Table 1), and is also as used in Brainwave
% Gong, G., He, Y., Concha, L., Lebel, C., Gross, D. W., Evans, A. C. & Beaulieu, C. Mapping anatomical connectivity patterns of human cerebral cortex using in vivo diffusion tensor imaging tractography. Cereb. Cortex 19, 524-536 (2009).
%
% Arjan Hillebrand, Jan 2012

VERSION = '1.0';
APPNAME = mfilename;
% disp(sprintf('%s V%s, (C) 2012, Arjan Hillebrand, KNF/MEG - VUmc', APPNAME, VERSION));

Gonglabels=strvcat(...
    'Gyrus rectus L',...
    'Olfactory cortex L',...
    'superior frontal gyrus, orbital part L',...
    'superior frontal gyrus, medial orbital L',...
    'middle frontal gyrus, orbital part L',...
    'inferior frontal gyrus, orbital part L',...
    'superior frontal gyrus, dorsolateral L',...
    'middle frontal gyrus L',...
    'inferior frontal gyrus, opercular part L',...
    'inferior frontal gyrus, triangular part L',...
    'superior frontal gyrus, medial L',...
    'supplementary motor area L',...
    'paracentral lobule L',...
    'precentral gyrus L',...
    'rolandic operculum L',...
    'postcentral gyrus L',...
    'superior parietal gyrus L',...
    'inferior parietal, but supramarginal and angular gyri L',...
    'supramarginal gyrus L',...
    'angular gyrus L',...
    'precuneus L',...
    'superior occipital gyrus L',...
    'middle occipital gyrus L',...
    'inferior occipital gyrus L',...
    'calcarine fissure and surrounding cortex L',...
    'cuneus L',...
    'lingual gyrus L',...
    'fusiform gyrus L',...
    'heschl gyrus L',...
    'superior temporal gyrus L',...
    'middle temporal gyrus L',...
    'inferior temporal gyrus L',...
    'temporal pole: superior temporal gyrus L',...
    'temporal pole: middle temporal gyrus L',...
    'parahippocampal gyrus L',...
    'anterior cingulate and paracingulate gyri L',...
    'median cingulate and paracingulate gyri L',...
    'posterior cingulate gyrus L',...
    'insula L',...
    'Gyrus rectus R',...
    'Olfactory cortex R',...
    'superior frontal gyrus, orbital part R',...
    'superior frontal gyrus, medial orbital R',...
    'middle frontal gyrus, orbital part R',...
    'inferior frontal gyrus, orbital part R',...
    'superior frontal gyrus, dorsolateral R',...
    'middle frontal gyrus R',...
    'inferior frontal gyrus, opercular part R',...
    'inferior frontal gyrus, triangular part R',...
    'superior frontal gyrus, medial R',...
    'supplementary motor area R',...
    'paracentral lobule R',...
    'precentral gyrus R',...
    'rolandic operculum R',...
    'postcentral gyrus R',...
    'superior parietal gyrus R',...
    'inferior parietal, but supramarginal and angular gyri R',...
    'supramarginal gyrus R',...
    'angular gyrus R',...
    'precuneus R',...
    'superior occipital gyrus R',...
    'middle occipital gyrus R',...
    'inferior occipital gyrus R',...
    'calcarine fissure and surrounding cortex R',...
    'cuneus R',...
    'lingual gyrus R',...
    'fusiform gyrus R',...
    'heschl gyrus R',...
    'superior temporal gyrus R',...
    'middle temporal gyrus R',...
    'inferior temporal gyrus R',...
    'temporal pole: superior temporal gyrus R',...
    'temporal pole: middle temporal gyrus R',...
    'parahippocampal gyrus R',...
    'anterior cingulate and paracingulate gyri R',...
    'median cingulate and paracingulate gyri R',...
    'posterior cingulate gyrus R',...
    'insula R');
       
    
ROI_indices=[27,21,5,25,9,15,3,7,11,13,23,19,69,1,17,57,59,61,63,65,67,49,51,53,43,45,47,55,79,81,85,89,83,87,39,31,33,35,29, ...
        28,22,6,26,10,16,4,8,12,14,24,20,70,2,18,58,60,62,64,66,68,50,52,54,44,46,48,56,80,82,86,90,84,88,40,32,34,36,30]';

    provide_feedback = 0;
    if provide_feedback
        disp(sprintf('\n\nLabel Gong et al.\t\t\t\tAAL label'))
        disp(sprintf('______________________________________________________________________'))
        for i=1:length(ROI_indices)
            disp(sprintf('%s\t\t\t\t%s',deblank(Gonglabels(i,:)), char(cfg.allnames{ROI_indices(i)})));
        end
    end




 